name: mrhisum
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _tflow_select=2.3.0
  - absl-py=1.4.0
  - aiohttp=3.8.3
  - aiosignal=1.3.1
  - astor=0.8.1
  - asttokens=2.2.1
  - astunparse=1.6.3
  - async-timeout=4.0.2
  - attrs=22.2.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - blas=2.116
  - blas-devel=3.9.0
  - blinker=1.5
  - brotlipy=0.7.0
  - c-ares=1.18.1
  - ca-certificates=2023.5.7
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cachetools=4.2.4
  - certifi=2023.5.7
  - cffi=1.14.6
  - charset-normalizer=2.1.1
  - click=8.1.3
  - colorama=0.4.6
  - comm=0.1.2
  - cryptography=39.0.0
  - cudatoolkit=11.0.3
  - debugpy=1.6.6
  - decorator=5.1.1
  - einops=0.6.1
  - executing=1.2.0
  - freetype=2.12.1
  - frozenlist=1.3.3
  - gast=0.3.3
  - google-auth=1.35.0
  - google-auth-oauthlib=0.4.6
  - google-pasta=0.2.0
  - grpcio=1.51.1
  - h5py=2.10.0
  - hdf5=1.10.6
  - icu=72.1
  - idna=3.4
  - importlib-metadata=6.0.0
  - importlib_metadata=6.0.0
  - intel-openmp=2022.1.0
  - ipykernel=6.21.2
  - ipython=8.10.0
  - jedi=0.18.2
  - joblib=1.2.0
  - jpeg=9b
  - jupyter_client=8.0.2
  - jupyter_core=5.2.0
  - keras-preprocessing=1.1.2
  - keyutils=1.6.1
  - krb5=1.20.1
  - ld_impl_linux-64=2.39
  - libabseil=20220623.0
  - libaec=1.0.6
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcurl=7.87.0
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.3
  - libgcc-ng=12.2.0
  - libgfortran-ng=12.2.0
  - libgfortran5=12.2.0
  - libgomp=12.2.0
  - libgrpc=1.51.1
  - libhwloc=2.9.1
  - libiconv=1.17
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libnghttp2=1.51.0
  - libopenblas=0.3.21
  - libpng=1.6.39
  - libprotobuf=3.21.12
  - libsodium=1.0.18
  - libsqlite=3.40.0
  - libssh2=1.10.0
  - libstdcxx-ng=12.2.0
  - libtiff=4.2.0
  - libuv=1.44.2
  - libwebp-base=1.2.4
  - libxml2=2.11.4
  - libzlib=1.2.13
  - llvm-openmp=15.0.7
  - lz4-c=1.9.3
  - markdown=3.4.1
  - markupsafe=2.1.2
  - matplotlib-inline=0.1.6
  - mkl=2022.1.0
  - mkl-devel=2022.1.0
  - mkl-include=2022.1.0
  - multidict=6.0.4
  - ncurses=6.3
  - nest-asyncio=1.5.6
  - ninja=1.11.0
  - numpy=1.20.2
  - oauthlib=3.2.2
  - olefile=0.46
  - openssl=1.1.1u
  - opt_einsum=3.3.0
  - packaging=23.0
  - pandas=1.4.4
  - parso=0.8.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=7.1.2
  - pip=22.3.1
  - platformdirs=3.0.0
  - prettytable=3.7.0
  - prompt-toolkit=3.0.36
  - protobuf=4.21.12
  - psutil=5.9.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pycparser=2.21
  - pygments=2.14.0
  - pyjwt=2.6.0
  - pyopenssl=23.0.0
  - pysocks=1.7.1
  - python=3.8.8
  - python-dateutil=2.8.2
  - python_abi=3.8
  - pytorch=1.7.1
  - pytz=2023.3
  - pyu2f=0.1.5
  - pyzmq=25.0.0
  - re2=2022.06.01
  - readline=8.1.2
  - requests=2.28.2
  - requests-oauthlib=1.3.1
  - rsa=4.9
  - scikit-learn=1.0.2
  - scipy=1.9.1
  - setuptools=66.1.1
  - six=1.16.0
  - sqlite=3.40.0
  - stack_data=0.6.2
  - tbb=2021.9.0
  - tensorboard=2.4.1
  - tensorboard-plugin-wit=1.8.1
  - tensorboardx=2.2
  - tensorflow=2.3.0
  - tensorflow-base=2.3.0
  - tensorflow-estimator=2.6.0
  - termcolor=2.2.0
  - threadpoolctl=3.1.0
  - tk=8.6.12
  - torchaudio=0.7.2
  - torchvision=0.8.2
  - tornado=6.2
  - tqdm=4.64.1
  - traitlets=5.9.0
  - typing-extensions=4.4.0
  - typing_extensions=4.4.0
  - urllib3=1.26.14
  - wcwidth=0.2.6
  - werkzeug=2.2.2
  - wheel=0.38.4
  - wrapt=1.14.1
  - xz=5.2.6
  - yarl=1.8.2
  - zeromq=4.3.4
  - zipp=3.11.0
  - zlib=1.2.13
  - zstd=1.4.9
  - pip:
      - ortools==9.5.2237